FRAMAC_SHARE := $(shell frama-c-config -print-share-path)
FRAMAC_LIBDIR := $(shell frama-c-config -print-libpath)
PLUGIN_NAME = Forgetful
PLUGIN_CMO = forgetful_plugin
include $(FRAMAC_SHARE)/Makefile.dynamic
